version: "3.8"
services:
  web:
    build:
      context: ./
      target: builder # Change target to 'builder'
    volumes:
      - .:/app
    command: npm run dev # Change the command to 'npm run dev'
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
