version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: development
